server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/team3_nhn_member?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: Lushlife99!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    instance-id: member-api-1
    hostname: localhost
