server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nhn_member?serverTimezone=UTC&characterEncoding=UTF-8
    username: chan
    password: chan1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

eureka:
  instance:
    instance-id: member-api
    hostname: localhost
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:1234@localhost:8761/eureka/
