server:
  port: 8083

spring:
  data:
    redis:
      host: s4.java21.net
      port: 6379
      database: 222
  datasource:
    url: jdbc:mysql://s4.java21.net:13306/project_be8_triple_seven_member?serverTimezone=UTC&characterEncoding=UTF-8
    username: project_be8_triple_seven
    password: eo1cItEUe@J2Tym
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

eureka:
  instance:
    health-check-url: /actuator/health
    instance-id: member-api
    hostname: localhost
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:1234@localhost:10138/eureka/


