spring:
  profiles:
    active: dev

  lifecycle:
    timeout-per-shutdown-phase: 30s
  application:
    name: member-api

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:1234@eureka-server:8761/eureka
  instance:
    prefer-ip-address: true

management:
  health:
    status:
      order: DOWN, UP
  endpoint:
    jolokia:
      enable: true
    pause:
      enabled: true
    resume:
      enabled: true

  info:
    env:
      enabled: true

server:
  shutdown: graceful

