server:
  port: 8083

spring:
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  datasource:
    url: jdbc:mysql://localhost:3306/msamemberapi?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

eureka:
  instance:
    health-check-url: /actuator/health
    instance-id: member-api
    hostname: localhost
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:1234@localhost:8761/eureka/


kakao:
  api:
    key: a647f3b0334d3e5914bdff0748674f64
