name: CI/CD Pipeline for Spring Boot Member Api

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml

      - name: Build Docker image
        run: |
          docker build -t lushlife99/nhn-member:${{ github.sha }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push lushlife99/nhn-member:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to First Instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker pull lushlife99/nhn-member:${{ github.sha }}
            if [ "$(docker ps -aq --filter "name=member-api-instance-1")" ]; then
              docker stop member-api-instance-1 || true
              docker rm -f member-api-instance-1 || true
            fi
              docker run -d --name member-api-instance-1 -p 8082:8082 -e SPRING_PROFILES_ACTIVE=instance1 lushlife99/nhn-member:${{ github.sha }}


      - name: Deploy to Second Instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker pull lushlife99/nhn-member:${{ github.sha }}
            if [ "$(docker ps -aq --filter "name=member-api-instance-2")" ]; then
              docker stop member-api-instance-2 || true
              docker rm -f member-api-instance-2 || true
            fi
              docker run -d --name member-api-instance-2 -p 8083:8083 -e SPRING_PROFILES_ACTIVE=instance2 lushlife99/nhn-member:${{ github.sha }}
