name: CI/CD Pipeline for Spring Boot Member Api

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run SonarQube analysis
        run: |
          mvn clean verify sonar:sonar \
          -Dsonar.projectKey=triple-seven-member-api \
          -Dsonar.projectName='triple-seven-member-api' \
          -Dsonar.host.url=http://133.186.241.167:9000 \
          -Dsonar.token=sqp_8fb843838fb8d2612093abab1fe723e5e69fe66f